### ISSUE TITLE
Unable to compile librdkafka

### ISSUE THREAD

**Issue by chakri-stark** [FooBarWidget/holy-build-box#17]
Hi,
I am unable to compile librdkafka (https://github.com/edenhill/librdkafka).
Steps:
I have logged into the container and activated hbb_exe
Configure of librdkafka throws out C++ not found

**Comment by FooBarWidget** [comment]
@chakri-stark is this issue still relevant? If so can you post error messages?

**Comment by FooBarWidget** [comment]
I'm closing this issue until more information arrives.
