### ISSUE TITLE
Undefined references to nearly all TBB symbols when built under holy build box

### ISSUE THREAD

**Issue by rob-p** [FooBarWidget/holy-build-box#54]
Hi,

  We use holy build box to build distributable linux executables for our software [salmon](https://github.com/COMBINE-lab/salmon).  Recently, we have been trying to update to a more recent version of the threading building blocks library (TBB), since some parts of the API have been deprecated in newer versions.  Unfortunately, after making this update, essentially all TBB-related symbols now fail to resolve when building under holy build box.

   I recently posted a full rundown of the issue in the TBB repo [here](https://github.com/oneapi-src/oneTBB/issues/779).  While I am not sure the ultimate *cause* of the problem, I can only replicate this issue reliably within holy build box.  On our server locally (ubuntu 16.04), on my Mac laptop, and on the GitHub CI images we use (ubuntu latest and OSX latest), everything builds cleanly.  Yet, in holy build box, we simply cannot get this library to link.  Interestingly, this was not a problem with the older versions of TBB, but those are now deprecated and maintenance & development is only done on the new versions, so we cannot stick with the old library in perpetuity.

  Any insight you might have into this would be greatly appreciated.

Thanks!
Rob

**Comment by FooBarWidget** [comment]
See https://github.com/oneapi-src/oneTBB/issues/779#issuecomment-1046269700. It's not a Holy Build Box problem, but rather one of proper usage of `-fvisibility=hidden`.
